name: Build and deploy .NET 9 app to Azure Web App - learningapp400

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build with dotnet
        run: dotnet build tmp2/learningapp/learningapp.csproj --configuration Release

      - name: Publish app
        run: dotnet publish tmp2/learningapp/learningapp.csproj -c Release -o published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: published

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F89F43B0C22C4DA4AA434C82778D18AD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F81FE13DDD54BCCB21F3164B8C66059 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0DDAFD9CCF484CA680C6A41A3EB48768 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'learningapp400'
          slot-name: 'Production'
          package: .
